var ERROR_INVALID_PASSWORDCONF = "Invalid password confirmation."
var ERROR_INTERNAL_SERVER = "Internal server error."
var ERROR_NOT_LOG = "You are not logged in."
var ERROR_USER_NOT_FOUND  = "User not found."
var ERROR_USER_NOT_FOUND  = "User not found."
var ERROR_INVALID_PASSWORD = "Invalid password."
var ERROR_TWEET_NOT_FOUND = "Tweet not found."

exports.ERROR_INTERNAL_SERVER = ERROR_INTERNAL_SERVER;
exports.ERROR_INVALID_PASSWORD = ERROR_INVALID_PASSWORD;
exports.ERROR_NOT_LOG = ERROR_NOT_LOG;
exports.ERROR_USER_NOT_FOUND = ERROR_USER_NOT_FOUND;
exports.ERROR_INVALID_PASSWORDCONF = ERROR_INVALID_PASSWORDCONF;
exports.ERROR_TWEET_NOT_FOUND = ERROR_TWEET_NOT_FOUND;